## NumPy (Numerical Python)
* NumPy는 Numerical Python의 약자로 과학 및 공학 분야에서 사용되는 오픈 소스 파이썬 라이브러이이다.
* NumPy 라이브러리에는 다차원 배열 및 행렬 데이터 구조가 포함되어 있다.
* NumPy는 배열로 저장된 값에 대한 수학 연산을 수행하는데 사용된다.
* [사용법]
  * 설치: pip install numpy
  * 호출: import numpy as np

In [1]:
!pip install numpy

You should consider upgrading via the 'C:\Temp\2025\venv310\Scripts\python.exe -m pip install --upgrade pip' command.


In [3]:
import numpy as np

city = ['서울', '부산', '광주']
print(city[1])

city2 = np.array(['서울', '부산', '광주'])
print(city2[1])

부산
부산


In [6]:
arr = np.array([2, 4, 6, 8, 10])
print(arr)
print(type(arr))
print(arr.dtype)

[ 2  4  6  8 10]
<class 'numpy.ndarray'>
int64


In [10]:
# 리스트

a = [1, 3, 5]
b = [2, 4, 6]
c = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# print(a * b) # 에러
print(a + b)
print(a[1] + b[1])
print(c * 3)

[1, 3, 5, 2, 4, 6]
7
[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
# 넘파이 (벡터화 연산: 1차원 배열을 한꺼번에 계산)
import numpy as np

a = np.array([1, 3, 5])
b = np.array([2, 4, 6])
c = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(a * b)
print(a + b)
print(a[1] + b[1])
print(c * 3)

[ 2 12 30]
[ 3  7 11]
7
[ 3  6  9 12 15 18 21 24 27]


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
c = np.array([1, 2])

print(a * b)
print(a + b)
print(b / a)

#print(a + c) # 크기가 다르면 에러

[10 40 90]
[11 22 33]
[10. 10. 10.]


In [ ]:
heights = np.array([170, 175, 160, 173])    # 키 (cm)
weights = np.array([65, 70, 55, 70])       # 몸무게 (kg)

# bmi: 몸무게 / (키/100) ** 2
bmi = weights / (heights/100)**2
print("BMI:", bmi)

BMI: [22.49134948 22.85714286 21.484375   23.38868656]


In [ ]:
import numpy as np

# 학생: 3개 (행단위)
# 과목: 4개 (열단위)
                   #과목1 과목2  과목3 과목4 
scores = np.array([[85,   90,   88,   95],      # 학생1
                   [92,   87,   85,   89],      # 학생2
                   [78,   85,   91,   87]])     # 학생3

# axis=0: 세로 방향 평균
# ↓ axis=0 행 (세로 방향)
# → axis=1 열 (가로 방향)
# 85 + 92 + 78 --> 85 (4번)

subjects_mean = scores.mean(axis=0)
print("과목별 평균:", subjects_mean)

student_mean = scores.mean(axis=1)
print("학생별 평균:", student_mean)

nml = scores - subjects_mean
print(nml)

과목별 평균: [85.         87.33333333 88.         90.33333333]
학생별 평균: [89.5  88.25 85.25]
[[ 0.          2.66666667  0.          4.66666667]
 [ 7.         -0.33333333 -3.         -1.33333333]
 [-7.         -2.33333333  3.         -3.33333333]]


In [23]:
# 학생들의 점수 (행: 학생, 열: 과목)
scores = np.array([[90, 85, 88, 75],    # 학생1
                   [85, 92, 87, 98],    # 학생2
                   [88, 86, 91, 90]])   # 학생3

# 과목별 가중치 (40%, 30%, 20%, 10%)
w = np.array([0.4, 0.3, 0.2, 0.1])
wscore = scores * w
print(wscore)

[[36.  25.5 17.6  7.5]
 [34.  27.6 17.4  9.8]
 [35.2 25.8 18.2  9. ]]


In [24]:
prices = np.array([12000, 35000, 8000, 45000, 28000])
discounts = np.array([10, 20, 5, 30, 15])

discount_amount = prices * (discounts/100)
fprice = prices - discount_amount

print("할인된 가격: ", fprice)

할인된 가격:  [10800. 28000.  7600. 31500. 23800.]


In [27]:
prices = np.array([50000, 150000, 250000, 80000, 120000])
## 할인율 조건: 10만원 미만 10%, 20만원 미만 15%, 20만원 이상 20% 할인

rate = []
for price in prices:
    if price < 100000:
        rate.append(10)
    elif price < 200000:
        rate.append(15)
    else:
        rate.append(20)

discounts = np.array(rate)
discount_amount = prices * (discounts/100)
fprice = prices - discount_amount
print("할인된 가격: ", fprice)

할인된 가격:  [ 45000. 127500. 200000.  72000. 102000.]


In [28]:
prices = np.array([50000, 150000, 250000, 80000, 120000])
## 할인율 조건: 10만원 미만 10%, 20만원 미만 15%, 20만원 이상 20% 할인

def discount_rate(price):
    if price < 100000:
        return 10
    elif price < 200000:
        return 15
    else:
        return 20

discounts = np.array([discount_rate(price) for price in prices])
discount_amount = prices * (discounts/100)
fprice = prices - discount_amount
print("할인된 가격: ", fprice)

할인된 가격:  [ 45000. 127500. 200000.  72000. 102000.]


In [29]:
# 섭씨 --> 화씨:  F = (C * 9/5) + 32
temps_c = np.array([[25, 27, 26, 24, 23],  # 서울
                    [28, 30, 29, 27, 26],  # 부산
                    [22, 24, 23, 21, 20]]) # 강릉

temps_f = (temps_c * 9/5) + 32
print("화씨 온도:\n",temps_f )

화씨 온도:
 [[77.  80.6 78.8 75.2 73.4]
 [82.4 86.  84.2 80.6 78.8]
 [71.6 75.2 73.4 69.8 68. ]]


In [31]:
import numpy as np

# 3개 지점의 일주일 매출 데이터(1~7일)
sales = np.array([[520000, 480000, 510000, 690000, 620000, 750000, 510000],  # 1호점
                  [480000, 460000, 490000, 670000, 580000, 710000, 490000],  # 2호점
                  [590000, 520000, 550000, 720000, 650000, 780000, 540000]]) # 3호점

daily_avg = sales.mean(axis=0)
print(daily_avg)

# 요일별 평균 대비 성과 (%) - 평균 대비 퍼센트
# ((판매액/일평균) * 100) - 100
performance = ((sales / daily_avg) * 100) - 100
print("요일별 평균 대비 성과 (%):\n", performance)

[530000.         486666.66666667 516666.66666667 693333.33333333
 616666.66666667 746666.66666667 513333.33333333]
요일별 평균 대비 성과 (%):
 [[-1.88679245 -1.36986301 -1.29032258 -0.48076923  0.54054054  0.44642857
  -0.64935065]
 [-9.43396226 -5.47945205 -5.16129032 -3.36538462 -5.94594595 -4.91071429
  -4.54545455]
 [11.32075472  6.84931507  6.4516129   3.84615385  5.40540541  4.46428571
   5.19480519]]


## 넘파이 : 다차원 배열

In [ ]:
# 스칼라: 하나의 데이터 값을 가진 배열 (0차원)
import numpy as np

arr = np.array(12)
print(arr)
print(type(arr))

print(np.shape(arr))  # 반환값 x

12
<class 'numpy.ndarray'>
()


In [37]:
# 벡터: 1차원 배열 (넘파이의 가장 기본적인 배열)
import numpy as np
arr = np.array([2, 4, 6, 8, 10, 12, 14])
print(arr)
print(np.shape(arr))

[ 2  4  6  8 10 12 14]
(7,)


In [ ]:
print(np.zeros(5))  # 0으로 채워진 1차원 배열 생성
print(np.ones(5))   # 1로 채워진 1차원 배열 생성
print(np.empty(5))  # 바로 값을 넣으려고 만든 경우
print(np.arange(5)) # 0 ~ 5 미만

arr = np.empty(5)
arr[:] = np.arange(1, 6)
print(arr)

print(np.arange(2, 20, 3))

print(np.linspace(0, 100, num = 5)) 
# 0부터 100까지 구간을 5개의 균등 간격으로 나눈 숫자들을 생성

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[0 1 2 3 4]
[1. 2. 3. 4. 5.]
[ 2  5  8 11 14 17]
[  0.  25.  50.  75. 100.]


In [45]:
scores = np.array([90, 80, 100, 85, 98])
print(scores)
scores = np.zeros(5)
print(scores)

[ 90  80 100  85  98]
[0. 0. 0. 0. 0.]


In [47]:
# 5명의 출석 상태를 1로 초기화
import numpy as np
num_students = 5
attendance = np.ones(num_students)
print("Attendance (All Present):", attendance)

attendance[1] = 0
print("Attendance:", attendance)

Attendance (All Present): [1. 1. 1. 1. 1.]
Attendance: [1. 0. 1. 1. 1.]


In [49]:
# 5명의 학생 점수를 0으로 초기화
import numpy as np
num_students = 5
scores = np.zeros(num_students)
print("Initial Scores:", scores)

scores[0] = 85
scores[1] = 90

print("Scores:", scores)

Initial Scores: [0. 0. 0. 0. 0.]
Scores: [85. 90.  0.  0.  0.]


In [51]:
# 2차원 배열 (행렬: 매트릭스) - 테이블 형태의 행과 열로 구성된 배열
import numpy as np
arr = np.array([
    [2, 4, 6],
    [1, 3, 5]
]) 
arr = np.array([[2, 4, 6],[1, 3, 5]]) # 2행 3열
print(arr)
print(np.shape(arr))

[[2 4 6]
 [1 3 5]]
(2, 3)


In [ ]:
import numpy as np
arr = np.array([[2, 4], [6, 8], [10, 12]]) #3행 2열
print(arr)
print(np.shape(arr))

[[ 2  4]
 [ 6  8]
 [10 12]]
(3, 2)


In [54]:
print(len(arr))  # 행의 갯수
print(len(arr[0]))  # 열의 갯수

3
2


In [ ]:
arr = np.array([[85, 90, 78, 92],
                [75, 80, 88, 70],
                [95, 100, 90, 85]])
print(np.shape(arr))

print(len(arr))    # 행 갯수
print(len(arr[0])) # 열 갯수

sz = np.shape(arr)
print(sz, type(sz))
print(sz[0], sz[1]) # 0: 행 갯수, 1: 열 갯수

(3, 4)
3
4
(3, 4) <class 'tuple'>
3 4


In [ ]:
# 5종 제품의 재고 수량과 가격
arr = np.array([[10, 100],  # 제품 1: 재고 10개, 가격 100원
                [5, 200],   # 제품 2: 재고 5개, 가격 200원
                [20, 50],   # 제품 3: 재고 20개, 가격 50원
                [0, 150],   # 제품 4: 재고 0개, 가격 150원
                [15, 80]])  # 제품 5: 재고 15개, 가격 80원

print(np.shape(arr))
print(len(arr))     # 행 수
print(len(arr[0]))  # 열 수
rowCnt, colCnt = arr.shape
print(rowCnt, colCnt)
print(arr.ndim) # 차원 수  (차원: 0 ~ 3)

(5, 2)
5
2
5 2
2


In [66]:
# 3차원 배열: 텐서 (2차원 배열을 몇 번 사용할거냐)
import numpy as np
arr = np.array([
                [[111, 112, 113], [121, 122, 123]],
                [[211, 212, 213], [221, 222, 223]],
                [[311, 312, 313], [321, 322, 323]],
                [[411, 412, 413], [421, 422, 423]]
               ])
print(np.shape(arr))
depth, rows, cols = np.shape(arr) # 튜플 반환
print(depth, rows, cols)

print(len(arr))           # 깊이(층)를 표시
print(len(arr[0]))        # 행의 개수를 표시
print(len(arr[0][0]))     # 열의 개수를 표시

(4, 2, 3)
4 2 3
4
2
3


In [ ]:
# 배열 재구성
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)
print(arr.shape)

#new1 = np.reshape(arr, (4, 3))
new1 = arr.reshape(4, 3)
new2 = arr.reshape(2, 6)
print(new1)
print(new2)

# 2차원 or 3차원 --> 1차원
new3 = new2.flatten()
print(new3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
new4 = arr.reshape(2, 3, 2)
print(new4)
print(new4.shape)
print(new4.ndim)

new5 = new4.flatten()
print(new5)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
## 넘파이 인덱싱

# 1차원 인덱싱
import numpy as np
arr = np.array([2, 4, 6, 8])
print(arr[3])

8


In [11]:
print(arr[1] + arr[3])
print(arr[1] * arr[3])

12
32


In [14]:
# 2차원 인덱싱
arr = np.array([[2, 4, 6], [1, 3, 5]])
print(arr)
print(arr[1, 1])

[[2 4 6]
 [1 3 5]]
3


In [19]:
# 3차원 인덱싱
import numpy as np
arr = np.array([[[11, 12, 13], [14, 15, 16]],
                [[21, 22, 23], [24, 25, 26]]])
print(arr)
print(arr.shape)

[[[11 12 13]
  [14 15 16]]

 [[21 22 23]
  [24 25 26]]]
(2, 2, 3)


In [18]:
print(arr[0, 0, 0])
print(arr[1, 0, 0])
print(arr[1, 1, 2])

11
21
26


In [20]:
import numpy as np
arr = np.array([2, 4, 6, 8])
print(arr[-1])

8


In [ ]:
import numpy as np
arr = np.array([[2, 4, 6], [1, 3, 5]])
print(arr.shape)

print(arr[1, -2])
print(arr[-1, -2])

(2, 3)
3
3


In [ ]:
# 특정 조건 데이터 인덱싱
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr.shape)
arr < 5

(3, 4)


array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [29]:
arr[arr < 11]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr[arr > 6]

array([ 7,  8,  9, 10, 11, 12])

In [30]:
arr[arr % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [31]:
arr % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [32]:
# 4 ~ 8 까지의 값만 추출 (&: and, |: or)
arr[(arr > 3) & (arr < 9)]

array([4, 5, 6, 7, 8])

In [33]:
import numpy as np
arr = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
print(arr[0])     # 인덱스 0번
print(arr[-1])    # 제일 뒤
print(arr[0:3])   # [시작번호:끝번호+1]
print(arr[:3])    # 처음부터 3번 앞까지
print(arr[4:])    # 4번부터 끝까지
print(arr[4:6])   # 4번부터 6번 앞까지
print(arr[4:-4])  # 4번부터 뒤에서 4번 앞까지

10
19
[10 11 12]
[10 11 12]
[14 15 16 17 18 19]
[14 15]
[14 15]


In [40]:
import numpy as np
scores = np.array([[85, 90, 75, 88],   # 1반
                   [92, 86, 78, 95],   # 2반
                   [89, 91, 84, 82]])  # 3반

# 1반의 모든 학생 각 점수, 인원수, 총점, 평균
print("1반 학생별 점수:", scores[0])
print("1반 인원수:", len(scores[0]))
print("1반 총점:", np.sum(scores[0]))
print("1반 평균:", np.mean(scores[0]))

print("각 반의 첫번째 학생:", scores[:,0])
print("각 반의 첫번째 학생 총점:", np.sum(scores[:,0]))
print("각 반의 첫번째 학생 평균:", np.mean(scores[:,0]))

1반 학생별 점수: [85 90 75 88]
1반 인원수: 4
1반 총점: 338
1반 평균: 84.5
각 반의 첫번째 학생: [85 92 89]
각 반의 첫번째 학생 총점: 266
각 반의 첫번째 학생 평균: 88.66666666666667
