# KNN(K-Nearest Neighbors)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier

df4 = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
df4.info()
df4

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
df4.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
# 비권장(새로운 값 들어올 시 문제 발생)
# df4['sepal_length'] = scaler.fit_transform(df4[['sepal_length']])
# df4['sepal_width'] = scaler.fit_transform(df4[['sepal_width']])
# df4['petal_length'] = scaler.fit_transform(df4[['petal_length']])
# df4['petal_width'] = scaler.fit_transform(df4[['petal_width']])

# 권장
df4[['sepal_length','sepal_width','petal_length','petal_width']] = scaler.fit_transform(df4[['sepal_length','sepal_width','petal_length','petal_width']])
df4

sepal_length  sepal_width  petal_length  petal_width    species
0        0.222222     0.625000      0.067797     0.041667     setosa
1        0.166667     0.416667      0.067797     0.041667     setosa
2        0.111111     0.500000      0.050847     0.041667     setosa
3        0.083333     0.458333      0.084746     0.041667     setosa
4        0.194444     0.666667      0.067797     0.041667     setosa
..            ...          ...           ...          ...        ...
145      0.666667     0.416667      0.711864     0.916667  virginica
146      0.555556     0.208333      0.677966     0.750000  virginica
147      0.611111     0.416667      0.711864     0.791667  virginica
148      0.527778     0.583333      0.745763     0.916667  virginica
149      0.444444     0.416667      0.694915     0.708333  virginica

[150 rows x 5 columns]

In [ ]:
# 독립변수(피처), 종속변수(타겟) 지정
X3 = df4[['sepal_length','sepal_width','petal_length','petal_width']]
y3 = df4['species']

In [ ]:
# 데이터셋 분리 (학습 : 테스트 = 8 : 2)
X3_train, X3_test, y3_train, y3_test = train_test_split(X3,y3,test_size = 0.2, random_state = 11)
print(X3_train.shape)
print(X3_test.shape)
print(y3_train.shape)
print(y3_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)


In [ ]:
# 학습
model = KNeighborsClassifier(n_neighbors=9)
model.fit(X3_train, y3_train)

KNeighborsClassifier(n_neighbors=9)

In [ ]:
# 예측
pred3 = model.predict(X3_test)
print('실제값:',y3_test.values)
print('예측값:',pred3)

실제값: ['virginica' 'virginica' 'virginica' 'versicolor' 'virginica' 'setosa'
 'versicolor' 'setosa' 'setosa' 'versicolor' 'virginica' 'versicolor'
 'versicolor' 'virginica' 'virginica' 'setosa' 'virginica' 'versicolor'
 'virginica' 'virginica' 'versicolor' 'setosa' 'setosa' 'versicolor'
 'setosa' 'setosa' 'virginica' 'versicolor' 'setosa' 'versicolor']
예측값: ['virginica' 'virginica' 'versicolor' 'versicolor' 'virginica' 'setosa'
 'versicolor' 'setosa' 'setosa' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'virginica' 'virginica' 'setosa' 'virginica' 'versicolor'
 'virginica' 'virginica' 'versicolor' 'setosa' 'setosa' 'versicolor'
 'setosa' 'setosa' 'virginica' 'versicolor' 'setosa' 'versicolor']


In [ ]:
# 성능확인
rep = classification_report(y3_test,pred3)
mat = confusion_matrix(y3_test,pred3)

print(rep)
print(mat)

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         9
  versicolor       0.83      1.00      0.91        10
   virginica       1.00      0.82      0.90        11

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.94      0.93      0.93        30

[[ 9  0  0]
 [ 0 10  0]
 [ 0  2  9]]


<pre>
아이리스 붓꽃(iris flower) 데이터셋에 대한 분류 모델의 성능 평가

[주요 지표 설명]
Precision (정밀도): 모델이 긍정으로 예측한 샘플 중 실제로 긍정인 샘플의 비율입니다. 높을수록 좋습니다.

Recall (재현율): 실제 긍정 샘플 중 모델이 긍정으로 올바르게 예측한 비율입니다. 이 값도 높을수록 좋습니다.

F1-score: 정밀도와 재현율의 조화 평균으로, 두 지표의 균형을 고려하여 평가합니다. 이 값이 높을수록 모델 성능이 좋습니다.

Support: 각 클래스에 대한 실제 샘플 수입니다.

[클래스별 성능]

Setosa

Precision: 1.00 (모든 예측이 정확)
Recall: 1.00 (모든 실제 샘플을 정확히 예측)
F1-score: 1.00 (완벽한 성능)
Support: 9 (총 9개 샘플)

Versicolor

Precision: 0.83 (예측한 10개 중 83%가 정확)
Recall: 1.00 (모든 실제 샘플을 정확히 예측)
F1-score: 0.91 (준수한 성능)
Support: 10 (총 10개 샘플)

Virginica

Precision: 1.00 (모든 예측이 정확)
Recall: 0.82 (82%의 실제 샘플을 정확히 예측)
F1-score: 0.90 (좋은 성능)
Support: 11 (총 11개 샘플)

[전체 성능]
Accuracy (정확도): 0.93 (전체 샘플 중 93%를 올바르게 예측)
Macro avg: 각 클래스의 평균 성능
Precision: 0.94
Recall: 0.94
F1-score: 0.94
Weighted avg: 각 클래스의 지원 수에 따라 가중 평균
Precision: 0.94
Recall: 0.93
F1-score: 0.93

[결론]
전체적으로 모델은 높은 성능을 보이며, 특히 "Setosa" 클래스에서 완벽한 예측을 달성했습니다. 
"Versicolor"와 "Virginica" 클래스에 대해서도 좋은 성능을 보입니다. 
다만, "Versicolor"의 정밀도가 다소 낮아 더 많은 데이터나 조정이 필요할 수 있습니다.
</pre>