In [445]:
import pandas as pd

df = pd.read_csv('csv/delay_proof_all.csv')
df2 = df.copy()
df2

날짜   노선   방향  첫차~09시 09시~18시 18시~막차
0      금일 (2025-09-16)  1호선  상행선     NaN     NaN    NaN
1      금일 (2025-09-16)  1호선  하행선     NaN     NaN    NaN
2      금일 (2025-09-16)  2호선   내선     NaN     NaN    NaN
3      금일 (2025-09-16)  2호선   외선  10분 지연     NaN    NaN
4      금일 (2025-09-16)  2호선   외선     NaN     NaN    NaN
..                 ...  ...  ...     ...     ...    ...
708  30일전 (2025-08-17)  7호선  석남행     NaN     NaN    NaN
709  30일전 (2025-08-17)  8호선  상행선     NaN     NaN    NaN
710  30일전 (2025-08-17)  8호선  하행선     NaN     NaN    NaN
711  30일전 (2025-08-17)  9호선  상행선     NaN     NaN    NaN
712  30일전 (2025-08-17)  9호선  하행선     NaN     NaN    NaN

[713 rows x 6 columns]

In [446]:
df2['노선'] = df2['노선'].str.split('호선').str[0]
df2

날짜 노선   방향  첫차~09시 09시~18시 18시~막차
0      금일 (2025-09-16)  1  상행선     NaN     NaN    NaN
1      금일 (2025-09-16)  1  하행선     NaN     NaN    NaN
2      금일 (2025-09-16)  2   내선     NaN     NaN    NaN
3      금일 (2025-09-16)  2   외선  10분 지연     NaN    NaN
4      금일 (2025-09-16)  2   외선     NaN     NaN    NaN
..                 ... ..  ...     ...     ...    ...
708  30일전 (2025-08-17)  7  석남행     NaN     NaN    NaN
709  30일전 (2025-08-17)  8  상행선     NaN     NaN    NaN
710  30일전 (2025-08-17)  8  하행선     NaN     NaN    NaN
711  30일전 (2025-08-17)  9  상행선     NaN     NaN    NaN
712  30일전 (2025-08-17)  9  하행선     NaN     NaN    NaN

[713 rows x 6 columns]

In [447]:
df2['첫차~09시'] = df2['첫차~09시'].str.split('분').str[0]
df2['첫차~09시'].unique()

array([nan, '10', '5', '15', '20', '30', '25'], dtype=object)

In [448]:
df2['09시~18시'] = df2['09시~18시'].str.split('분').str[0]
df2['09시~18시'].unique()

array([nan, '5', '10'], dtype=object)

In [449]:
df2['18시~막차'] = df2['18시~막차'].str.split('분').str[0]
df2['18시~막차'].unique()

array([nan, '10'], dtype=object)

In [450]:
df2.fillna(0, inplace=True)
df2

날짜 노선   방향 첫차~09시 09시~18시 18시~막차
0      금일 (2025-09-16)  1  상행선      0       0      0
1      금일 (2025-09-16)  1  하행선      0       0      0
2      금일 (2025-09-16)  2   내선      0       0      0
3      금일 (2025-09-16)  2   외선     10       0      0
4      금일 (2025-09-16)  2   외선      0       0      0
..                 ... ..  ...    ...     ...    ...
708  30일전 (2025-08-17)  7  석남행      0       0      0
709  30일전 (2025-08-17)  8  상행선      0       0      0
710  30일전 (2025-08-17)  8  하행선      0       0      0
711  30일전 (2025-08-17)  9  상행선      0       0      0
712  30일전 (2025-08-17)  9  하행선      0       0      0

[713 rows x 6 columns]

In [451]:
df2.loc[df2['노선'] == '신정지선',['노선','방향']] = [2,'신정지선']

In [452]:
df2['날짜'] = pd.to_datetime(df2['날짜'].str.split('(').str[1].str.split(')').str[0], errors="coerce")
df2['노선'] = df2['노선'].astype(int)
df2['방향'] = df2['방향'].astype(str)
df2['첫차~09시'] = df2['첫차~09시'].astype(int)
df2['09시~18시'] = df2['09시~18시'].astype(int)
df2['18시~막차'] = df2['18시~막차'].astype(int)
df2.info()
print(type(df2['18시~막차'][0]))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 713 entries, 0 to 712
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype         
---  ------   --------------  -----         
 0   날짜       713 non-null    datetime64[ns]
 1   노선       713 non-null    int64         
 2   방향       713 non-null    object        
 3   첫차~09시   713 non-null    int64         
 4   09시~18시  713 non-null    int64         
 5   18시~막차   713 non-null    int64         
dtypes: datetime64[ns](1), int64(4), object(1)
memory usage: 33.5+ KB
<class 'numpy.int64'>


In [453]:
df2.to_csv('delay_subway.csv', index=False)

In [454]:
import sqlalchemy

engine = sqlalchemy.create_engine("mysql+pymysql://root:1234@192.168.0.115/miniproject")
df2.to_sql(name='delay_subway', con=engine, if_exists='replace', index=False)
query = "SELECT * FROM delay_subway"
df3 = pd.read_sql(query, engine)
df3.info()
df3

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 713 entries, 0 to 712
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype         
---  ------   --------------  -----         
 0   날짜       713 non-null    datetime64[ns]
 1   노선       713 non-null    int64         
 2   방향       713 non-null    object        
 3   첫차~09시   713 non-null    int64         
 4   09시~18시  713 non-null    int64         
 5   18시~막차   713 non-null    int64         
dtypes: datetime64[ns](1), int64(4), object(1)
memory usage: 33.5+ KB


날짜  노선   방향  첫차~09시  09시~18시  18시~막차
0   2025-09-16   1  상행선       0        0       0
1   2025-09-16   1  하행선       0        0       0
2   2025-09-16   2   내선       0        0       0
3   2025-09-16   2   외선      10        0       0
4   2025-09-16   2   외선       0        0       0
..         ...  ..  ...     ...      ...     ...
708 2025-08-17   7  석남행       0        0       0
709 2025-08-17   8  상행선       0        0       0
710 2025-08-17   8  하행선       0        0       0
711 2025-08-17   9  상행선       0        0       0
712 2025-08-17   9  하행선       0        0       0

[713 rows x 6 columns]

In [455]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
df3.info()
df3

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 713 entries, 0 to 712
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype         
---  ------   --------------  -----         
 0   날짜       713 non-null    datetime64[ns]
 1   노선       713 non-null    int64         
 2   방향       713 non-null    object        
 3   첫차~09시   713 non-null    int64         
 4   09시~18시  713 non-null    int64         
 5   18시~막차   713 non-null    int64         
dtypes: datetime64[ns](1), int64(4), object(1)
memory usage: 33.5+ KB


날짜  노선   방향  첫차~09시  09시~18시  18시~막차
0   2025-09-16   1  상행선       0        0       0
1   2025-09-16   1  하행선       0        0       0
2   2025-09-16   2   내선       0        0       0
3   2025-09-16   2   외선      10        0       0
4   2025-09-16   2   외선       0        0       0
..         ...  ..  ...     ...      ...     ...
708 2025-08-17   7  석남행       0        0       0
709 2025-08-17   8  상행선       0        0       0
710 2025-08-17   8  하행선       0        0       0
711 2025-08-17   9  상행선       0        0       0
712 2025-08-17   9  하행선       0        0       0

[713 rows x 6 columns]

In [456]:
# 데이터 변환
df3_long = df3.melt(
    id_vars=["날짜", "노선", "방향"],
    value_vars=["첫차~09시", "09시~18시", "18시~막차"],
    var_name="시간대",
    value_name="최대지연분"
)
df3_long["지연여부"] = (df3_long["최대지연분"] > 0).astype(int)
df3_long

날짜  노선   방향     시간대  최대지연분  지연여부
0    2025-09-16   1  상행선  첫차~09시      0     0
1    2025-09-16   1  하행선  첫차~09시      0     0
2    2025-09-16   2   내선  첫차~09시      0     0
3    2025-09-16   2   외선  첫차~09시     10     1
4    2025-09-16   2   외선  첫차~09시      0     0
...         ...  ..  ...     ...    ...   ...
2134 2025-08-17   7  석남행  18시~막차      0     0
2135 2025-08-17   8  상행선  18시~막차      0     0
2136 2025-08-17   8  하행선  18시~막차      0     0
2137 2025-08-17   9  상행선  18시~막차      0     0
2138 2025-08-17   9  하행선  18시~막차      0     0

[2139 rows x 6 columns]

In [457]:
# 라벨 인코딩
from sklearn.preprocessing import LabelEncoder
le_dir = LabelEncoder()
le_time = LabelEncoder()
df3_long["방향_label"] = le_dir.fit_transform(df3_long["방향"])
df3_long["시간대_label"] = le_time.fit_transform(df3_long["시간대"])
df3_long

날짜  노선   방향     시간대  최대지연분  지연여부  방향_label  시간대_label
0    2025-09-16   1  상행선  첫차~09시      0     0         4          2
1    2025-09-16   1  하행선  첫차~09시      0     0        13          2
2    2025-09-16   2   내선  첫차~09시      0     0         0          2
3    2025-09-16   2   외선  첫차~09시     10     1         9          2
4    2025-09-16   2   외선  첫차~09시      0     0         9          2
...         ...  ..  ...     ...    ...   ...       ...        ...
2134 2025-08-17   7  석남행  18시~막차      0     0         5          1
2135 2025-08-17   8  상행선  18시~막차      0     0         4          1
2136 2025-08-17   8  하행선  18시~막차      0     0        13          1
2137 2025-08-17   9  상행선  18시~막차      0     0         4          1
2138 2025-08-17   9  하행선  18시~막차      0     0        13          1

[2139 rows x 8 columns]

In [458]:
# 입력/출력
X = df3_long[["노선", "방향_label", "시간대_label"]]
y_class = df3_long["지연여부"]     # 분류용
y_reg = df3_long["최대지연분"]     # 회귀용

In [459]:
# 분리
X_train, X_test, y_train_class, y_test_class, y_train_reg, y_test_reg = train_test_split(
    X, y_class, y_reg, test_size=0.3, random_state=42, stratify=y_class
)
print(X_train.shape, X_test.shape, y_train_class.shape, y_test_class.shape, y_train_reg.shape, y_test_reg.shape)

(1497, 3) (642, 3) (1497,) (642,) (1497,) (642,)


In [460]:
# 1) 분류 모델
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
clf = LogisticRegression()
clf.fit(X_train, y_train_class)
print("=== 지연 발생 확률 분류 ===")
print(classification_report(y_test_class, clf.predict(X_test)))

=== 지연 발생 확률 분류 ===
              precision    recall  f1-score   support

           0       0.92      1.00      0.96       591
           1       0.00      0.00      0.00        51

    accuracy                           0.92       642
   macro avg       0.46      0.50      0.48       642
weighted avg       0.85      0.92      0.88       642



c:\Temp\2025\venv310\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Temp\2025\venv310\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Temp\2025\venv310\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [461]:
# 2) 회귀 모델
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error
reg = RandomForestRegressor()
reg.fit(X_train, y_train_reg)
y_pred_reg = reg.predict(X_test)
print("\n=== 최대 지연시간 예측 ===")
print("RMSE : 예측의 오차범위(분) - 큰 오차에 민감")
print("RMSE :", np.sqrt(mean_squared_error(y_test_reg, y_pred_reg)))
print("MAE : 예측의 오차범위(분) - 직관적이고 평균적인 분포")
print("MAE :", mean_absolute_error(y_test_reg, y_pred_reg))


=== 최대 지연시간 예측 ===
RMSE : 예측의 오차범위(분) - 큰 오차에 민감
RMSE : 1.9806978129820803
MAE : 예측의 오차범위(분) - 직관적이고 평균적인 분포
MAE : 0.7198116161098008


In [462]:
import re
# ---------------------------- 유틸 ----------------------------
def parse_user_time(t):
    """
    사용자가 입력한 시간(예: '10시', ' 9 ', 15)을 0~23 범위의 정수로 변환.
    """
    if isinstance(t, int):
        hour = t
    else:
        s = str(t).strip()
        m = re.search(r"\d{1,2}", s)
        if not m:
            raise ValueError("시간 형식을 인식하지 못했습니다. 예: '10시' 또는 10")
        hour = int(m.group())
    if not (0 <= hour <= 23):
        raise ValueError("시간은 0~23 사이여야 합니다.")
    return hour

def hour_to_timeband(hour: int) -> str:
    """
    정수 시(hour)를 시간대 문자열로 변환.
    - 0~8  -> '첫차~09시'
    - 9~17 -> '09시~18시'
    - 18~23-> '18시~막차'
    """
    if hour <= 8:
        return "첫차~09시"
    elif hour <= 17:
        return "09시~18시"
    else:
        return "18시~막차"
    
def make_query_df(line_no: int, direction: str, hour_input):
    """
    사용자 입력(노선, 방향, 시간)을 표준화된 DataFrame으로 변환.
    반환 컬럼: ['노선', '방향', '시간대']
    """
    hour = parse_user_time(hour_input)
    timeband = hour_to_timeband(hour)
    return pd.DataFrame({
        "노선": [int(line_no)],
        "방향": [str(direction)],
        "시간대": [timeband]
    })


In [463]:
def transform_inputs(le_dir, le_time, df_query: pd.DataFrame) -> pd.DataFrame:
    """
    학습된 LabelEncoder(le_dir, le_time)로 df_query의 '방향', '시간대'를 숫자로 변환.
    - 학습 때 보지 못한 범주가 들어오면 에러를 발생시켜 명확히 알림.
    반환 컬럼: ['노선', '방향_label', '시간대_label']
    """
    required = {"노선", "방향", "시간대"}
    missing = required - set(df_query.columns)
    if missing:
        raise ValueError(f"예측 입력에 필요한 컬럼이 없습니다: {missing}")

    # 학습 때 없던 범주 확인
    unknown_dir = set(df_query["방향"]) - set(le_dir.classes_)
    unknown_time = set(df_query["시간대"]) - set(le_time.classes_)
    if unknown_dir:
        raise ValueError(f"학습에 없던 방향 값이 있습니다: {unknown_dir}. "
                        f"허용 값: {list(le_dir.classes_)}")
    if unknown_time:
        raise ValueError(f"학습에 없던 시간대 값이 있습니다: {unknown_time}. "
                        f"허용 값: {list(le_time.classes_)}")

    dir_ids = le_dir.transform(df_query["방향"])
    time_ids = le_time.transform(df_query["시간대"])

    X = pd.DataFrame({
        "노선": df_query["노선"].astype(int),
        "방향_label": dir_ids.astype(int),
        "시간대_label": time_ids.astype(int)
    })
    return X

In [464]:
def predict_for_user(clf, reg, le_dir, le_time, line_no: int, direction: str, hour_input):
    """
    사용자 입력(노선, 방향, 시간)으로 예측 결과 DataFrame을 반환.
    - 지연발생확률(%): 분류모델의 양성(1) 확률 × 100
    - 예측_최대지연분: 회귀모델의 예측(음수 방지로 0 클리핑)
    - 기대_지연분: 확률 × 예측_최대지연분
    """
    # 1) 질의 정규화
    q = make_query_df(line_no, direction, hour_input)

    # 2) 학습 시 인코더로 같은 방식의 변환
    X = transform_inputs(le_dir, le_time, q)

    # 3) 분류 확률 산출 (양성 클래스를 1로 가정)
    #    혹시라도 clf가 단일 클래스만 학습되었다면 방어 로직 추가
    if hasattr(clf, "classes_") and len(clf.classes_) == 2:
        # classes_가 [0,1] 순서라고 보장되진 않으니 index로 찾아서 사용
        pos_index = np.where(clf.classes_ == 1)[0][0]
        proba = clf.predict_proba(X)[:, pos_index]
    else:
        # 이례적 상황: 분류가 사실상 한 클래스만 학습된 경우
        # predict_proba가 없거나 classes_가 1개뿐이면 지연확률을 0 또는 1로 고정
        proba = np.clip(clf.predict(X).astype(float), 0, 1)

    # 4) 회귀 예측 (음수 방지)
    y_hat = np.clip(reg.predict(X), 0, None)

    # 5) 기대 지연분(확률×분)
    expected = proba * y_hat

    # 6) 보기 좋은 출력
    out = q.copy()
    out["지연발생확률(%)"] = np.round(proba * 100.0, 2)
    out["예측_최대지연분"] = np.round(y_hat, 2)
    out["기대_지연분"] = np.round(expected, 2)
    return out

In [479]:
input_data = [1,"하행선",23]
result = predict_for_user(clf, reg, le_dir, le_time, line_no=input_data[0], direction=input_data[1], hour_input=input_data[2])
print(result)

   노선   방향     시간대  지연발생확률(%)  예측_최대지연분  기대_지연분
0   1  하행선  18시~막차      12.23      0.42    0.05
